apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-pv-claim
  labels:
    app: gitea
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
